/* Autogenerated by hxtools bin2c */
#include "res.h"
#include <wx/bitmap.h>
#include <wx/image.h>
#include <wx/mstream.h>
wxBitmap *bin2c_pinoff_png;
wxBitmap *bin2c_pinon_png;
void bin2c_init_RES_H(void)
{
	{
		wxMemoryInputStream sm("\211PNG\15\12\32\12\0\0\0\15IHDR\0\0\0\15\0\0\0\15\10\4\0\0\0\330\342,\367\0\0\0\4gAMA\0\0\261\217\13\374a\5\0\0\0008IDAT\30\323c`\240\01440\374\307%\365\377\377\177\6\4l@\223B\0\230\11\15\20\225\377\377#T\301\244\20j1\244\340\2720\15\304c\27A\0276\240\13\220\7\0\341FU/R\32\341f\0\0\0\0IEND\256B`\202", 129);
		bin2c_pinoff_png = new wxBitmap(wxImage(sm, wxBITMAP_TYPE_ANY), -1);
	}
	{
		wxMemoryInputStream sm("\211PNG\15\12\32\12\0\0\0\15IHDR\0\0\0\15\0\0\0\15\10\4\0\0\0\330\342,\367\0\0\0\4gAMA\0\0\261\217\13\374a\5\0\0\0FIDAT\30\323\215\216A\12\0 \14\303\252\350M\374\362\366\363*\"\242\262\241\3311t\4x\242\340:=\25%J\341\240\313K\5I\276\312\236\212\366J\207\252Km!<\331w3\235N>`$|(\265^\2314f\220V\330\24Ll\30\0\0\0\0IEND\256B`\202", 143);
		bin2c_pinon_png = new wxBitmap(wxImage(sm, wxBITMAP_TYPE_ANY), -1);
	}
}
