/* Autogenerated by hxtools bin2c */
#ifndef RES_H
#define RES_H 1

class wxBitmap;

extern "C" void bin2c_init_RES_H(void);
extern wxBitmap *bin2c_pinoff_png;
extern wxBitmap *bin2c_pinon_png;


#endif /* RES_H */
